# SPDX-FileCopyrightText: 2026 kotoverse
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
