version = 1
SPDX-PackageName = "Re:Likes"
SPDX-PackageSupplier = "kotoverse <https://github.com/kotoverse>"
SPDX-PackageDownloadLocation = "https://github.com/reinventinglikes/relikes"

[[annotations]]
path = [
  "package.json",
  "assets/relikes-logo.png",
  "backend/php/documents.json",
  "backend/php/example-reactions.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 kotoverse"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "wordpress/relikes/LICENSE",
  "wordpress/relikes/readme.txt"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 kotoverse"
SPDX-License-Identifier = "GPL-2.0-or-later"
